version: '3.8'
services:
  uc-intg-xbox:
    build: .
    container_name: uc-intg-xbox
    restart: unless-stopped
    network_mode: host
    environment:
      # THE FIX IS HERE: Set a specific, approved port for the integration
      - UC_PORT=9123
    volumes:
      - /volume1/docker/uc-intg-xbox/config:/app/uc_intg_xbox/config