services:
  intg-xbox-uc:
    container_name: intg-xbox-uc
    image: xbox-uc
    network_mode: host
    environment:
      
UC_INTEGRATION_HTTP_PORT=9094
  volumes:
./config:/config
restart: unless-stopped