services:
  intg-xbox-uc:
    container_name: uc-intg-xbox
    image: uc-xbox
    network_mode: host
    environment:
    UC_INTEGRATION_HTTP_PORT: 9094
  volumes: /volume1/docker/uc-intg-xbox/config:/config
restart: unless-stopped