version: '3.8'
services:
  uc-intg-xbox:
    build: .
    container_name: uc-intg-xbox
    restart: unless-stopped
    network_mode: host
    environment:
      - UC_INTEGRATION_HTTP_PORT=9094
      - UC_CONFIG_HOME=/config
    volumes:
      - ./config:/config
