version: '3.8'
services:
  uc-intg-xbox:
    build: .
    container_name: uc-intg-xbox
    restart: unless-stopped
    network_mode: host
    # THE FIX IS HERE: Set the environment variable for the ucapi library
    environment:
      - UC_ADDRESS=0.0.0.0
    volumes:
      - /volume1/docker/uc-intg-xbox/config:/app/uc_intg_xbox/config