FROM python:3.11-slim-bullseye

WORKDIR /app

# Install git and build tools (required for xbox-webapi git installation)
RUN apt-get update && apt-get install -y git build-essential && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt
RUN mkdir /config

ADD . .

ENV UC_DISABLE_MDNS_PUBLISH="false"
ENV UC_MDNS_LOCAL_HOSTNAME=""

ENV UC_INTEGRATION_INTERFACE="0.0.0.0"
ENV UC_INTEGRATION_HTTP_PORT="9094"

ENV UC_CONFIG_HOME="/config"
LABEL org.opencontainers.image.source=https://github.com/mase1981/uc-intg-xbox

CMD ["python3", "-u", "uc_intg_xbox/driver.py"]