version: '3.8'
services:
  uc-intg-xbox:
    build: .
    container_name: uc-intg-xbox
    restart: unless-stopped
    # Use host networking so the Unfolded Circle remote can discover it
    network_mode: host
    volumes:
      # This links a 'config' folder on your host machine to the container
      # to permanently store your authentication tokens.
      - ./config:/app/uc_intg_xbox/config