name: Create Release Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Install dependencies and official build tool
        # THE FIX IS HERE: Use the correct package name 'uc-build-utils'
        run: pip install . uc-build-utils

      - name: Build the Python wheel
        run: python -m build --wheel

      - name: Build the final distributable package using uc-build
        run: python -m uc_build --outdir dist dist/*.whl

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/uc_intg_xbox-*.tar.gz
          asset_name: uc-intg-xbox-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip