name: Create Release Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    # --- THE FIX IS HERE ---
    # Grant the workflow permission to write to releases
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get version from tag
        id: tag_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/uc_intg_xbox-${{ env.RELEASE_VERSION }}.tar.gz
          asset_name: uc_intg_xbox-${{ env.RELEASE_VERSION }}.tar.gz
          asset_content_type: application/gzip