name: "Build & Draft Release"

on:
  workflow_dispatch:

env:
  INTG_NAME: xbox
  PYTHON_VER: 3.11.12-0.3.0

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version-and-id.outputs.VERSION }}
      driver_id: ${{ steps.get-version-and-id.outputs.DRIVER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 200

      - name: Get version and id
        id: get-version-and-id
        run: |
          echo "VERSION=$(jq .version -r driver.json)" >> $GITHUB_ENV
          echo "DRIVER_ID=$(jq .driver_id -r driver.json)" >> $GITHUB_ENV
          echo "VERSION=$(jq .version -r driver.json)" >> $GITHUB_OUTPUT
          echo "DRIVER_ID=$(jq .driver_id -r driver.json)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-system binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          echo "Starting pyinstaller build"
          docker run --rm --name builder \
            --platform=aarch64 \
            --user=$(id -u):$(id -g) \
            -v ${GITHUB_WORKSPACE}:/workspace \
            docker.io/unfoldedcircle/r2-pyinstaller:${PYTHON_VER} \
            bash -c \
            "cd /workspace && \
             python -m pip install -r requirements.txt && \
             pyinstaller --clean --onedir --name intg-${DRIVER_ID} \
             --collect-all zeroconf \
             --collect-all httpx \
             --collect-all pydantic \
             uc_intg_xbox/driver.py" # CORRECTED: Use correct source path uc_intg_xbox/

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts/bin
          # CORRECTED: The executable is in a subfolder, not the root of dist/
          mv dist/*/* artifacts/bin
          # CORRECTED: The executable has the name we gave it, not 'driver' yet
          mv artifacts/bin/intg-${{ env.DRIVER_ID }} artifacts/bin/driver
          cp driver.json artifacts/
          echo "ARTIFACT_NAME=uc-intg-${{ env.DRIVER_ID }}-${{ env.VERSION }}-aarch64" >> $GITHUB_ENV
          
      - name: Create upload artifact archive
        shell: bash
        run: | 
          tar czvf ${{ env.ARTIFACT_NAME }}.tar.gz -C ${GITHUB_WORKSPACE}/artifacts .
          ls -lah
          
      - uses: actions/upload-artifact@v4
        id: upload_artifact
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.tar.gz
          if-no-files-found: error
          retention-days: 3
            
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Extract build archives from downloaded files
        run: |
          ls -R
          for D in * do if [ -d "${D}" ]; then
              mv $D/* ./
            fi
          done;

      - name: Create hash file
        run: |
          for filename in *.tar.gz; do echo "sha256  `sha256sum $filename`" >> ${{needs.build.outputs.driver_id}}.hash; done;

      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz,${{needs.build.outputs.driver_id}}.hash"
          draft: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          tag: v${{needs.build.outputs.version}}