name: Create Release Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create package structure
        run: |
          mkdir -p dist/package/bin/_internal
          cp driver.json dist/package/

      - name: Create executable script
        run: |
          echo '#!/bin/sh' > dist/package/bin/uc_intg_xbox
          echo 'python3 -m uc_intg_xbox.driver' >> dist/package/bin/uc_intg_xbox
          chmod +x dist/package/bin/uc_intg_xbox

      - name: Install dependencies and source code into the package
        run: |
          pip install --target=dist/package/bin/_internal -r requirements.txt
          cp -r uc_intg_xbox dist/package/bin/_internal/

      - name: Create the final .tar.gz archive
        run: tar -czf uc-intg-xbox-${{ steps.get_version.outputs.VERSION }}.tar.gz -C dist/package .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./uc-intg-xbox-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: uc-intg-xbox-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip